services:
  backend:
    build: ./backend
    container_name: mental-health-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_S3_REGION=${AWS_S3_REGION:-us-east-1}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET:-mental-health-app-audio-bucket}
    volumes:
      - backend-data:/app/uploads
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: mental-health-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data:
    driver: local
